name: extended_navbar_scaffold
description: A Custom Extended Scaffold with Expandable and Floating Navigation Bar
version: 1.0.0

author: Ketan Choyal <ketanchoyal@gmail.com>
homepage: https://github.com/ketanchoyal/extended_navbar_scaffold

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eva_icons_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

